// app.tsx
import React from "react";
import { StatusBar, StyleSheet, Text, View } from "react-native";

export default function App() {
    return (
        <View style={styles.container}>
            <StatusBar barStyle="light-content" />
            <Text style={styles.text}>Open up app.tsx to start working on your app!</Text>
        </View>
    );
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#141414",
        alignItems: "center",
        justifyContent: "center",
    },

    text: {
        color: "#999",
    },
});

// src/app.vue
<template>
    <view class="container">
        <status-bar background-color="#141414" bar-style="light-content" />
    </view>
</template>

<script>
    export default {
        name: "app",

        mounted() {
            this.$scanner.start();
        },
    };
</script>

<style>
    .container {
        background-color: #141414;
        align-items: center;
        justify-content: center;
        flex: 1;
    }

    .text {
        color: #999;
    }
</style>
